const LOADING_USER = 'LOADING_USER'
const CURRENT_USER = 'CURRENT_USER'
const FINISHED_LOADING_USER = 'FINISHED_LOADING_USER'
const LOGOUT_USER = 'LOGOUT_USER'

export {
  LOADING_USER,
  LOGOUT_USER,
  CURRENT_USER,
  FINISHED_LOADING_USER,
}
